import image from "./img";

// 画像についてimg/image.jsで定義している。
// pidを属性（メソッド）にして管理する方針

const data = [
  {
    pid: "ofuda_family_safety",
    image: image.ofuda_family_safety,
    category: "御神札",
    name: { "御神札": 0 },
    types: { "家内安全": 0 },
    colors: {},
    price: 800,
    weight: 23,

  },
  {
    pid: "ofuda_yaku_yoke",
    image: image.ofuda_yaku_yoke,
    category: "御神札",
    name: { "御神札": 0 },
    types: { "方除・魔除・赤札": 0 },
    colors: {},
    price: 500,
    weight: 23,
  },
  {
    pid: "ofuda_sen_ryu",
    image: image.ofuda_sen_ryu,
    category: "御神札",
    name: { "御神札": 0 },
    types: { "潜龍大神": 0 },
    colors: {},
    price: 800,
    weight: 23,
  },
  {
    pid: "thokon_tukusu_mamori",
    image: image.thokon_tukusu_mamori,
    category: "御守",
    name: { "闘魂尽す守（マグネット式）": 0 },
    types: {},
    colors: { "赤": 0, "黒": 0 },
    price: 800,
    weight: 7,
  },
  {
    pid: "kyugi_thokon_mamori",
    image: image.kyugi_thokon_mamori,
    category: "御守",
    name: { "球技闘魂守（角）": 0 },
    types: {},
    colors: { "青": 0, "赤": 0, "白": 0 },
    price: 700,
    weight: 7,
  },
  {
    pid: "thokon_mamori_kado",
    image: image.thokon_mamori_kado,
    category: "御守",
    name: { "闘魂守（角）": 0 },
    types: {},
    colors: { "青": 0, "赤": 0, "白": 0, "黒地・青文字": 0, "黒地・赤文字": 0, "黒地・金文字": 0 },
    price: 700,
    weight: 7,
  },
  {
    pid: "thokon_mamori_maru",
    image: image.thokon_mamori_maru,
    category: "御守",
    name: { "闘魂守（丸）": 0 },
    types: {},
    colors: { "青": 0, "赤": 0, "白": 0, "黒地・金文字": 0 },
    price: 700,
    weight: 7,
  },
  {
    pid: "kisei_mamori",
    image: image.kisei_mamori,
    category: "御守",
    name: { "祈星守": 0 },
    types: {},
    colors: {
      "青地・紐白": 0,
      "青地・紐橙": 0,
      "白地・紐白": 0,
      "白地・紐橙": 0,
      "白地・紐青": 0,
      "黒地・紐青": 0,
      "黒地・紐橙": 0,
    },
    price: 800,
    weight: 6,
  },
  {
    pid: "deau_wa",
    image: image.deau_wa,
    category: "授与品",
    name: { "出逢う輪": 0 },
    types: {},
    colors: {},
    price: 800,
    weight: 9,
  },
  {
    pid: "mori_ya",
    image: image.mori_ya,
    category: "授与品",
    name: { "守り矢": 0 },
    types: { "スポーツ上達": 0, "必勝祈願": 0, "開運厄除": 0, "社運隆昌": 0, "心願成就": 0 },
    colors: {},
    price: 1500,
    weight: 260,
  },
  {
    pid: "hama_ya",
    image: image.hama_ya,
    category: "授与品",
    name: { "破魔矢": 0 },
    types: {},
    colors: {},
    price: 700,
    weight: 21,
  },
  {
    pid: "traffic_safety_sticker",
    image: image.traffic_safety_sticker,
    category: "授与品",
    name: { "交通安全ステッカー": 0 },
    types: {},
    colors: {},
    price: 700,
    weight: 5,
  },
  {
    pid: "traffic_safety_car_mamori",
    image: image.traffic_safety_car_mamori,
    category: "授与品",
    name: { "交通安全車体守": 0 },
    types: {},
    colors: {},
    price: 700,
    weight: 11,
  },
  {
    pid: "kanau_wa_gosyoku",
    image: image.kanau_wa_gosyoku,
    category: "授与品",
    name: { "『五色版』叶う輪": 0 },
    types: { "台紙：白黒": 0, "台紙：緑": 0 },
    colors: {},
    price: 800,
    weight: 10,
  },
  // {
  //   pid: "kanau_wa",
  //   image: image.dummy,
  //   category: "授与品",
  //   name: { "叶う輪": 0 },
  //   types: {},
  //   colors: { "赤": 0, "青": 0, "黄": 0, "緑": 0 },
  //   price: 800,
  //   weight: 11,
  // },
  {
    pid: "kanau_wa_soccer",
    image: image.kanau_wa_soccer,
    category: "授与品",
    name: { "叶う輪―サッカー、フットサル": 0 },
    types: {},
    colors: { "赤": 0, "青": 0, "黄": 0, "緑": 0 },
    price: 800,
    weight: 10,
  },
  {
    pid: "kanau_wa_baseball",
    image: image.kanau_wa_baseball,
    category: "授与品",
    name: { "叶う輪―野球、ソフトボール": 0 },
    types: {},
    colors: { "赤": 0, "青": 0, "黄": 0, "緑": 0 },
    price: 800,
    weight: 10,
  },
  {
    pid: "kanau_wa_volley",
    image: image.kanau_wa_volley,
    category: "授与品",
    name: { "叶う輪―バレー、ビーチバレー": 0 },
    types: {},
    colors: { "赤": 0, "青": 0, "黄": 0, "緑": 0 },
    price: 800,
    weight: 10,
  },
  {
    pid: "kanau_wa_basket",
    image: image.kanau_wa_basket,
    category: "授与品",
    name: { "叶う輪―バスケットボール": 0 },
    types: {},
    colors: { "赤": 0, "青": 0, "黄": 0, "緑": 0 },
    price: 800,
    weight: 10,
  },
  {
    pid: "kanau_wa_tennis",
    image: image.kanau_wa_tennis,
    category: "授与品",
    name: { "叶う輪―テニス、スカッシュ": 0 },
    types: {},
    colors: { "赤": 0, "青": 0, "黄": 0, "緑": 0 },
    price: 800,
    weight: 10,
  },
  {
    pid: "kanau_wa_badminton",
    image: image.kanau_wa_badminton,
    category: "授与品",
    name: { "叶う輪―バドミントン": 0 },
    types: {},
    colors: { "赤":0, "青":0, "黄":0, "緑": 0 },
    price: 800,
    weight: 10,
  },
  {
    pid: "kanau_wa_table_tennis",
    image: image.kanau_wa_table_tennis,
    category: "授与品",
    name: { "叶う輪―卓球": 0 },
    types: {},
    colors: { "赤": 0, "青": 0, "黄": 0, "緑": 0 },
    price: 800,
    weight: 10,
  },
  {
    pid: "kanau_wa_all",
    image: image.kanau_wa_all,
    category: "授与品",
    name: { "叶う輪―全般": 0 },
    types: {},
    colors: { "赤": 0, "青": 0, "黄": 0, "緑": 0 },
    price: 800,
    weight: 10,
  },
  {
    pid: "hair_band",
    image: image.hair_band,
    category: "授与品",
    name: { "ヘアバンド": 0 },
    types: {},
    colors: {
      "白": 0,
      "赤": 0,
      "黄": 0,
      "紫": 0,
      "黒": 0,
      "ピンク": 0,
      "青": 0,
      "橙": 0,
      "グリーン": 0,
      "濃紺": 0,
    },
    price: 800,
    weight: 10,
  },
  {
    pid: "wrist_band",
    image: image.wrist_band,
    category: "授与品",
    name: { "リストバンド": 0 },
    types: {},
    colors: { "青": 0, "赤": 0, "黒": 0, "白": 0, "黄": 0 },
    price: 800,
    weight: 24,
  },
  {
    pid: "towel",
    image: image.towel,
    category: "授与品",
    name: { "タオル": 0 },
    types: { "ロングタオル": 0, "赤・青1組": 0 },
    colors: {},
    price: 500,
    weight: 75,
  },
  // {
  //   pid: "towel",
  //   image: image.towel,
  //   category: "授与品",
  //   name: { "タオル（赤・青 1組）": 0 },
  //   types: { "サイズ：タテ約30cm×ヨコ約40cm": 0 },
  //   colors: {},
  //   price: 500,
  //   weight: 75,
  // },
  // {
  //   pid: "towel_long",
  //   image: image.towel_long,
  //   category: "授与品",
  //   name: { "ロングタオル": 0 },
  //   types: { "サイズ：タテ約36cm×ヨコ約84cm": 0 },
  //   colors: {},
  //   price: 500,
  //   weight: 80,
  // },
  {
    pid: "ema_sky",
    image: image.ema_sky,
    category: "授与品",
    name: { "絵馬（心願成就）": 0 },
    types: { "銀河・黒": 0, "宵の明星・青": 0, "明の明星・茜": 0 },
    colors: {},
    price: 800,
    weight: 50,
  },
  {
    pid: "ema",
    image: image.ema,
    category: "授与品",
    name: { "絵馬": 0 },
    types: { "スポーツ系": 0, "恋愛成就": 0, "文化系": 0 },
    colors: {},
    price: 800,
    weight: 40,
  },
  {
    pid: "kanau_wa_hashi",
    image: image.kanau_wa_hashi,
    category: "授与品",
    name: { "叶う和箸": 0 },
    types: { "心願成就・黄": 0, "除災招福・赤": 0 },
    colors: {},
    price: 800,
    weight: 8,
  },
  // {
  //   pid: "syuin_chou",
  //   image: image.syuin_chou,
  //   category: "授与品",
  //   name: { "御朱印帳": 0 },
  //   types: { "御朱印帳": 0, "限定御朱印帳": 0 },
  //   colors: {},
  //   price: 2000,
  //   weight: 180,
  // },
  {
    pid: "mari_dorei",
    image: image.mari_dorei,
    category: "授与品",
    name: { "まり土鈴": 0 },
    types: {},
    colors: {},
    price: 1500,
    weight: 260,
  },
  {
    pid: "ba_tei",
    image: image.ba_tei,
    category: "授与品",
    name: { "馬蹄": 0 },
    types: {},
    colors: { "金": 0, "銀": 0 },
    price: 700,
    weight: 13,
  },
  {
    pid: "yui_syo",
    image: image.yui_syo,
    category: "授与品",
    name: { "由緒（朱印付き）": 0 },
    types: {},
    colors: {},
    price: 300,
    weight: 27,
  },
];

export default data;